
package com.vn.fsoft.bidding.ejb.ws.endpoints;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bidService", targetNamespace = "http://endpoints.ws.ejb.bidding.fsoft.vn.com/", wsdlLocation = "http://localhost:8080/bidding-system-ejb/bidService/BidWS?wsdl")
public class BidService
    extends Service
{

    private final static URL BIDSERVICE_WSDL_LOCATION;
    private final static WebServiceException BIDSERVICE_EXCEPTION;
    private final static QName BIDSERVICE_QNAME = new QName("http://endpoints.ws.ejb.bidding.fsoft.vn.com/", "bidService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/bidding-system-ejb/bidService/BidWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIDSERVICE_WSDL_LOCATION = url;
        BIDSERVICE_EXCEPTION = e;
    }

    public BidService() {
        super(__getWsdlLocation(), BIDSERVICE_QNAME);
    }

    public BidService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIDSERVICE_QNAME, features);
    }

    public BidService(URL wsdlLocation) {
        super(wsdlLocation, BIDSERVICE_QNAME);
    }

    public BidService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIDSERVICE_QNAME, features);
    }

    public BidService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BidService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BidWS
     */
    @WebEndpoint(name = "BidWSPort")
    public BidWS getBidWSPort() {
        return super.getPort(new QName("http://endpoints.ws.ejb.bidding.fsoft.vn.com/", "BidWSPort"), BidWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BidWS
     */
    @WebEndpoint(name = "BidWSPort")
    public BidWS getBidWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoints.ws.ejb.bidding.fsoft.vn.com/", "BidWSPort"), BidWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIDSERVICE_EXCEPTION!= null) {
            throw BIDSERVICE_EXCEPTION;
        }
        return BIDSERVICE_WSDL_LOCATION;
    }

}
