
package com.vn.fsoft.bidding.ejb.ws.endpoints;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BidWS", targetNamespace = "http://endpoints.ws.ejb.bidding.fsoft.vn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BidWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.vn.fsoft.bidding.ejb.ws.endpoints.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://endpoints.ws.ejb.bidding.fsoft.vn.com/", className = "com.vn.fsoft.bidding.ejb.ws.endpoints.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://endpoints.ws.ejb.bidding.fsoft.vn.com/", className = "com.vn.fsoft.bidding.ejb.ws.endpoints.GetItemResponse")
    public List<Item> getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Account arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.vn.fsoft.bidding.ejb.ws.endpoints.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBid", targetNamespace = "http://endpoints.ws.ejb.bidding.fsoft.vn.com/", className = "com.vn.fsoft.bidding.ejb.ws.endpoints.GetBid")
    @ResponseWrapper(localName = "getBidResponse", targetNamespace = "http://endpoints.ws.ejb.bidding.fsoft.vn.com/", className = "com.vn.fsoft.bidding.ejb.ws.endpoints.GetBidResponse")
    public Bid getBid(
        @WebParam(name = "arg0", targetNamespace = "")
        Account arg0);

}
